version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "maven"
    directory: "/samples/java"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/samples/javascript"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/samples/typescript-axios"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
