#!/bin/bash
set -ex

SWAGGER_VERSION=2.4.0
SWAGGER_JAR=swagger-codegen-cli-${SWAGGER_VERSION}.jar
SWAGGER_DOWNLOAD_URL=http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/${SWAGGER_VERSION}/${SWAGGER_JAR}

if [[ ! -f ${SWAGGER_JAR} ]]; then
    echo "Local swagger-codegen jar not found. We'll download it now then run your command"
    wget wget  ${SWAGGER_DOWNLOAD_URL} -O ${SWAGGER_JAR}
fi

exec java -jar ${SWAGGER_JAR} "$@"
