ResourceId:
  name: resourceId
  in: path
  required: true
  description: The resource ID.
  type: string
WebhookPostRequest:
  name: webhookBody
  in: body
  required: true
  description: New webhook.
  schema:
    type: object
    properties:
      url:
        example: https://example.com/example
        type: string
        description: The URL of the remote webhook.
      secret:
        example: <password>
        type: string
        description: If sign is true, and the secret attribute is omitted, LaunchDarkly will automatically generate a secret for you.
      sign:
        type: boolean
        description: If sign is false, the webhook will not include a signature header, and the secret can be omitted.
      on:
        type: boolean
        example: true
        description: Whether this webhook is enabled or not.
    required:
      - url
      - sign
      - on
FeatureFlagPostRequest:
  name: featureFlagBody
  in: body
  required: true
  description: Create a new feature flag.
  schema:
    type: object
    properties:
      name:
        type: string
        description: A human-friendly name for the feature flag. Remember to note if this flag is intended to be temporary or permanent.
        example: "new test flag"
      key:
        type: string
        description: A unique key that will be used to reference the flag in your code.
        example: "new-test-flag"
      variations:
        type: array
        items:
          $ref: '#/definitions/Variation'
        description: An array of possible variations for the flag.
      temporary:
        type: boolean
        description: Whether or not the flag is a temporary flag.
      tags:
        type: array
        items:
          type: string
          example: '[]'
        description: Tags for the feature flag.
      includeInSnippet:
        type: boolean
        description: Whether or not this flag should be made available to the client-side JavaScript SDK.
    required:
      - name
      - key
      - variations
ProjectPostRequest:
  name: projectBody
  in: body
  required: true
  description: Project keys must be unique within an account.
  schema:
    type: object
    properties:
      name:
        type: string
        example: New Project
      key:
        type: string
        example: new-project
    required:
      - name
      - key
EnvironmentPostRequest:
  name: environmentBody
  in: body
  required: true
  description: New environment.
  schema:
    type: object
    properties:
      name:
        type: string
        description: The name of the new environment.
        example: Development
      key:
        type: string
        description: A project-unique key for the new environment.
        example: dev
      color:
        type: string
        description: A color swatch (as an RGB hex value with no leading '#', e.g. C8C8C8).
        example: "417505"
      defaultTtl:
        type: number
        description: The default TTL for the new environment.
        example: 0
    required:
      - name
      - key
      - color
ProjectKey:
  name: projectKey
  in: path
  required: true
  description: The project key, used to tie the flags together under one project so they can be managed together.
  type: string
EnvironmentKey:
  name: environmentKey
  in: path
  required: true
  description: The environment key, used to tie together flag configuration and users under one environment so they can be managed together.
  type: string
EnvironmentKeyQuery:
  name: env
  in: query
  required: false
  description: By default, each feature will include configurations for each environment. You can filter environments with the env query parameter. For example, setting env=production will restrict the returned configurations to just your production environment.
  type: string
FeatureFlagKey:
  name: featureFlagKey
  in: path
  required: true
  description: The feature flag's key. The key identifies the flag in your code.
  type: string
UserKey:
  name: userKey
  in: path
  required: true
  description: The user's key.
  type: string
Tag:
  name: tag
  in: query
  required: false
  description: Filter by tag. A tag can be used to group flags across projects.
  type: string
Limit:
  name: limit
  in: query
  required: false
  description: Pagination limit.
  type: integer
Query:
  name: q
  in: query
  required: false
  description: Search query.
  type: string
Offset:
  name: offset
  in: query
  required: false
  description: Specifies the first item to return in the collection.
  type: integer
After:
  name: after
  in: query
  required: false
  description: A timestamp filter, expressed as a Unix epoch time in milliseconds. All entries returned will have occured after this timestamp.
  format: int64
  type: number
PatchRequest:
  name: patchDelta
  in: body
  required: true
  description: Requires a JSON Patch representation of the desired changes to the project. 'http://jsonpatch.com/'
  schema:
    type: array
    items:
      type: object
      properties:
        op:
          type: string
          example: replace
        path:
          type: string
          example: '/on'
        value:
          type: object
      required:
        - op
        - path
        - value
UserSettingsPutRequest:
  name: userSettingsBody
  in: body
  required: true
  schema:
    type: object
    properties:
      setting:
        type: boolean
        description: >
          The variation value to set for the user. Must match the variation type of
          the flag.
Before:
  name: before
  in: query
  required: false
  description: A timestamp filter, expressed as a Unix epoch time in milliseconds. All entries returned will have before this timestamp.
  type: number
Q:
  name: q
  in: query
  required: false
  description: Text to search for. You can search for the full or partial name of the resource involved or fullpartial email address of the member who made the change.
  type: string
AuditLimit:
  name: limit
  in: query
  required: false
  description: A limit on the number of audit log entries to be returned, between 1 and 20.
  type: number
Spec:
  name: spec
  in: query
  required: false
  description: A resource specifier, allowing you to filter audit log listings by resource.
  type: string
MembersPostRequest:
  name: membersBody
  in: body
  required: true
  description: New members to invite.
  schema:
    type: array
    items:
      type: object
      properties:
        email:
          type: string
          example: exampleuser@email.com
        firstName:
          type: string
          example: Bob
        lastName:
          type: string
          example: Loblaw
        role:
          $ref: '#/definitions/Role'
        customRoles:
          type: array
          items:
            $ref: '#/definitions/CustomRoleKeyOrId'
        inlineRole:
          $ref: '#/definitions/Statements'
      required:
        - email
MemberId:
  name: memberId
  in: path
  required: true
  description: The member ID.
  type: string
CustomRolePostRequest:
  name: customRoleBody
  in: body
  required: true
  description: New role or roles to create.
  schema:
    type: object
    properties:
      name:
        type: string
        description: Name of the custom role.
        example: "revenue team"
      description:
        type: string
        description: Description of the custom role.
        example: "Description of revenue team role here"
      key:
        $ref: '#/definitions/CustomRoleKeyOrId'
      policy:
        type: array
        items:
          $ref: '#/definitions/Policy'
    required:
      - name
      - key
      - policy
CustomRoleKey:
  name: customRoleKey
  in: path
  required: true
  description: The custom role key.
  type: string
PatchWithComment:
  name: patchComment
  in: body
  required: true
  description: Requires a JSON Patch representation of the desired changes to the project. 'http://jsonpatch.com/' Feature flag patches also support JSON Merge Patch format. 'https://tools.ietf.org/html/rfc7386' The addition of comments is also supported.
  schema:
    type: object
    properties:
      comment:
        type: string
        example: "This is a comment string"
      patch:
        type: array
        items:
          type: object
          properties:
            op:
              type: string
              example: replace
            path:
              type: string
              example: '/description'
            value:
              type: object
              example: "The new description"
          required:
            - op
            - path
            - value

