on:
  workflow_call:

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.15'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          mkdir -p /go/src/github.com/launchdarkly
          cp -r targets/api-client-go /go/src/github.com/launchdarkly/
      - run: make
        working-directory: samples/go
        env:
          LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}