on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test-go:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          mkdir -p /home/runner/go/src/github.com/launchdarkly
          cp -r targets/api-client-go /home/runner/go/src/github.com/launchdarkly/
      - run: make
        working-directory: samples/go

  test-javascript:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: npm install
        working-directory: targets/api-client-javascript
      - run: |
          npm link $GITHUB_WORKSPACE/targets/api-client-javascript
          node --experimental-modules index.js
        working-directory: samples/javascript
      

  test-python:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          pip install -e ../../targets/api-client-python
          python main.py
        working-directory: samples/python

  test-ruby:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          gem build launchdarkly_api.gemspec
          gem install ./launchdarkly_api*.gem
        working-directory: targets/api-client-ruby
      - run: ruby main.rb
        working-directory: samples/ruby

  test-java:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'corretto'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: mvn clean install
        working-directory: targets/api-client-java
      - run: | # TODO: Need to fix the tag below
          sed -i.bak -e "s/API_CLIENT_VERSION/${{ inputs.version }}/g" pom.xml
          mvn clean install
          mvn exec:java
        working-directory: samples/java

  test-typescript:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          npm install
          npm run build
          npm link
        working-directory: targets/api-client-typescript-axios
      - run: |
          npm link launchdarkly-api-typescript
          npm install
          npm run build
          npm start
        working-directory: samples/typescript-axios

  test-php:
    runs-on: ubuntu-latest
    env:
      LD_API_KEY: ${{ secrets.TEMP_LD_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/download-artifact@v4
        with:
          name: targets
          path: ./targets
      - run: |
          echo '{"require":{"launchdarkly/api-client-php":"@dev","guzzlehttp/guzzle":"*"},"repositories":[{"type":"path","url":"../../targets/api-client-php","options":{"symlink":true}}]}' > composer.json 
          composer update
          php index.php
        working-directory: samples/php